[snowflake]
account = "SANOFI-EMEA_DF_MIS"
user = "PRANAVASHOK.CHAUDHARI@SANOFI.COM"
authenticator = "externalbrowser"
role = "DP_LCSPTRL_KEY_DEVELOPER"
warehouse = "DP_LCSPTRL_WH_LOAD"
database = "DP_LCSPTRL"
schema = "TEST_SNOWPARK"

[deprecation]
showPyplotGlobalUse = false
